# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: E. Krapavickaite Photography
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Sass settings
sass:
  add_charset: true
  sass_dir: assets/sass
  style: :compressed

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - README.md
  - CNAME
  - node_modules

# Plugin settings
gems:
  - jekyll-feed
  - jekyll-sitemap

#  images
images:
  - image_full_path: images/fulls/01.jpg
    image_thumb_path: images/thumbs/01.jpg
    title: You really got me
    width: 282
  - image_full_path: images/fulls/02.jpg
    image_thumb_path: images/thumbs/02.jpg
    title: Ad Infinitum
  - image_full_path: /images/fulls/03.jpg
    image_thumb_path: /images/thumbs/03.jpg
    title: Different.
  - image_full_path: /images/fulls/04.jpg
    image_thumb_path: /images/thumbs/04.jpg
    title: Elysium
  - image_full_path: /images/fulls/05.jpg
    image_thumb_path: /images/thumbs/05.jpg
    title: Kingdom of the Wind
  - image_full_path: /images/fulls/06.jpg
    image_thumb_path: /images/thumbs/06.jpg
    title: The Pursuit
  - image_full_path: /images/fulls/07.jpg
    image_thumb_path: /images/thumbs/07.jpg
    title: Boundless
  - image_full_path: /images/fulls/08.jpg
    image_thumb_path: /images/thumbs/08.jpg
    title: The Spectators
  - image_full_path: /images/fulls/01.jpg
    image_thumb_path: /images/thumbs/01.jpg
    title: You really got me
  - image_full_path: /images/fulls/02.jpg
    image_thumb_path: /images/thumbs/02.jpg
    title: Ad Infinitum
  - image_full_path: /images/fulls/03.jpg
    image_thumb_path: /images/thumbs/03.jpg
    title: Different.
  - image_full_path: /images/fulls/04.jpg
    image_thumb_path: /images/thumbs/04.jpg
    title: Elysium
  - image_full_path: /images/fulls/05.jpg
    image_thumb_path: /images/thumbs/05.jpg
    title: Kingdom of the Wind
  - image_full_path: /images/fulls/06.jpg
    image_thumb_path: /images/thumbs/06.jpg
    title: The Pursuit
  - image_full_path: /images/fulls/07.jpg
    image_thumb_path: /images/thumbs/07.jpg
    title: Boundless
  - image_full_path: /images/fulls/08.jpg
    image_thumb_path: /images/thumbs/08.jpg
    title: The Spectators
  - image_full_path: /images/fulls/09.jpg
    image_thumb_path: /images/thumbs/09.jpg
    title: Winter Wonderland
    width: 550

# Footer info
footer: <strong>Welcome to Erika Krapavickaite Photography</strong><br>
  Thank you for visiting my site.<br>I hope you enjoy looking at the images and would love to hear from you.

# social networks
social:
  twitter: https://twitter.com/AgneNevulyte
  linkedin: https://www.linkedin.com/in/agne-nevulyte-511895106?trk=hp-identity-name
  facebook: https://www.facebook.com/agne.nevulyte
  instagram: https://www.instagram.com/agne.nev/
  pinterest: https://www.pinterest.com/agnenevulyte/
  mail: mailto:agne.nevulyte@gmail.com



